<a href="https://colab.research.google.com/github/venkataratnamb20/quicksilicon/blob/notebooks/notebooks/vlsi/pyadc/pyadc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ADC

In [36]:
from dataclasses import dataclass

@dataclass
class Adc:
    nbit: int = 10
    vrefp: float = 1.0
    vrefm: float = 0.0
    fs: float = 10e3
    # def __post_init__(self, nbit: int = 10, vrefp: float = 1.0, vrefm: float = 0.0, fs: float = 1e3):
    #     self.nbit = nbit
    #     self.vrefp = vrefp
    #     self.vrefm = vrefm
    #     self.fs = fs

    @property
    def vref(self):
        return self.vrefp - self.vrefm

    @property
    def qlevels(self):
        return 2**self.nbit

    @property
    def lsb(self):
        return self.vref / (self.qlevels - 1)

    @property
    def sqnref(self):
        return 6.02 * self.nbit + 1.76

    @property
    def fclk(self):
        return self.fs * (self.nbit + 2)

    @property
    def tsample(self):
        return 1 / self.fs

    def convert(self, vin: float = 0.0):
        if vin > self.vrefp:
            vin = self.vref
        elif vin < self.vrefm:
            vin = self.vrefm
        return round(vin / self.lsb)

    def sar(self, vin: float = 0.0):
        raise NotImplementedError("Wait for the best tohappen!!!")

    def __str__(self):
        return f"""
        ADC(nbit = {self.nbit}, vrefp = {self.vrefp}, vrefm = {self.vrefm}, fs = {self.fs})"""

    def __repr__(self):
        return self.__str__()

    def __call__(self, vin: float = 0.0):
        return self.convert(vin)


adc = Adc(nbit = 10, vrefp = 1.0, vrefm = 0.0, fs = 10e3)
print(adc)

        ADC(nbit = 10, vrefp = 1.0, vrefm = 0.0, fs = 10000.0)

In [37]:
nbit = 10

for i in range(nbit + 2):
    vin = (2**i) * adc.lsb
    print(f"{vin} -> {adc(vin)}")

0.0009775171065493646 -> 1
0.0019550342130987292 -> 2
0.0039100684261974585 -> 4
0.007820136852394917 -> 8
0.015640273704789834 -> 16
0.03128054740957967 -> 32
0.06256109481915934 -> 64
0.12512218963831867 -> 128
0.25024437927663734 -> 256
0.5004887585532747 -> 512
1.0009775171065494 -> 1023
2.0019550342130987 -> 1023

In [3]:
class SarAdc(Adc):
    def __init__(self, nbit: int = 10, vrefp: float = 0.0, vrefm: float = 0.0, fs: float = 10e3, *args, **kwargs):
        super().__init__(nbit, vrefp, vrefm, fs, *args, **kwargs)
        self.nbit = nbit
        self.vrefp = vrefp
        self.vrefm = vrefm
        self.fs = fs
        self. low_level = self.vrefm
        self.high_level = self.vrefp
        self.code = []

    def comparator(self, vin: float = 0.0, vthresh: float = 0.0):
        return vin > vthresh

    def sar(self, vin: float = 0, *args, **kwargs):
        """Successive Approximation algorithm

        Args:
            vin (float, optional): input voltage. Defaults to 0.
            lower_level (float): lower level voltage. Defaults to 0.
            upper_level (float): upper level voltage. Defaults to 0.

        Returns:
            int: output voltage.
        """
        # nbit = kwargs.get("nbit", 10)
        # vrefm, vrefp = kwargs.get("vrefm", self.vrefm), kwargs.get("vrefp", self.vrefp)
        low_level, high_level = self.vrefm, self.vrefp
        code = []
        def algorithm(low_level: float = self.vrefm, high_level: float  =self.vrefp):
            # vthresh = low_level + (high_level - low_level) / 2
            vthresh = (high_level - low_level) / 2
            # print(f"levels:: low: {low_level} high: {high_level}")
            # print(f"vthresh: {vthresh}")
            decision = int(vin > low_level + vthresh)
            # decision = vin >= vthresh
            code.append(decision)
            if not decision:
                high_level = high_level - vthresh
            else:
                low_level = low_level + vthresh
            if len(code) == self.nbit:
                return code
            else:
                return algorithm(low_level, high_level)
        return algorithm(low_level, high_level)

    def __call__(self, vin: float = 0.0):
        self.code = []
        return self.sar(vin, self.vrefm, self.vrefp)


if __name__ == "__main__":
    saradc = SarAdc()
    print(f"nbit: {saradc.nbit}:: lsb: {saradc.lsb}")
    print(saradc(16 * adc.lsb))
    nbit = 10
    get_analog_from_bits_array = lambda code_list: int(''.join([str(bit) for bit in code_list]), 2)

    for i in range(nbit + 2):
        vin = (2**i) * adc.lsb
        print(f"{2**i}: {vin} \t->\t {saradc(vin)}::{get_analog_from_bits_array(saradc(vin))}")

nbit: 10:: lsb: 0.0
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
1: 0.0009775171065493646 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
2: 0.0019550342130987292 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
4: 0.0039100684261974585 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
8: 0.007820136852394917 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
16: 0.015640273704789834 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
32: 0.03128054740957967 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
64: 0.06256109481915934 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
128: 0.12512218963831867 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
256: 0.25024437927663734 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
512: 0.5004887585532747 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
1024: 1.0009775171065494 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023
2048: 2.0019550342130987 	->	 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::1023

## SAR

### SAR: Logic

In [38]:
def sar(vin, *args, **kwargs):
    """Successive Approximation algorithm

    """
    nbit = kwargs.get("nbit", 10)
    vrefm, vrefp = kwargs.get("vrefm", 0), kwargs.get("vrefp", 1.0)
    low_level, high_level = vrefm, vrefp
    lsb = (vrefp - vrefm) / (2**nbit - 1)
    code = []
    def algorithm(vin, low_level, high_level):
        # vthresh = low_level + (high_level - low_level) / 2
        vthresh = (high_level - low_level) / 2
        # print(f"levels:: low: {low_level} high: {high_level}")
        # print(f"vthresh: {vthresh}")
        decision = int(vin > low_level + vthresh)
        # decision = vin >= vthresh
        code.append(decision)
        if not decision:
            high_level = high_level - vthresh
        else:
            low_level = low_level + vthresh
        if len(code) == nbit:
            return code
        else:
            return algorithm(vin, low_level, high_level)
    return algorithm(vin, low_level, high_level)

sar(0.75)

[1, 0, 1, 1, 1, 1, 1, 1, 1, 1]

In [39]:
nbit = 12
vrefp = 1.5

adc = Adc(nbit = nbit, vrefp = vrefp)
print(adc)

get_analog_from_bits_array = lambda code_list: int(''.join([str(bit) for bit in code_list]), 2)

for i in range(nbit + 2):
    vin = (2**i) * adc.lsb
    # print(f"{vin} -> {sar(vin)}::{int(''.join([str(bit) for bit in sar(vin)]), 2)}")
    print(f"{2**i}: {vin} -> {sar(vin, nbit= nbit, vrefp = vrefp)}::{get_analog_from_bits_array(sar(vin, nbit= nbit, vrefp = vrefp))}")

        ADC(nbit = 12, vrefp = 1.5, vrefm = 0.0, fs = 10000.0)
1: 0.0003663003663003663 -> [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]::1
2: 0.0007326007326007326 -> [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]::2
4: 0.0014652014652014652 -> [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]::4
8: 0.0029304029304029304 -> [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]::8
16: 0.005860805860805861 -> [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]::16
32: 0.011721611721611722 -> [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]::32
64: 0.023443223443223443 -> [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]::64
128: 0.046886446886446886 -> [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]::128
256: 0.09377289377289377 -> [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]::256
512: 0.18754578754578755 -> [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]::512
1024: 0.3750915750915751 -> [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]::1024
2048: 0.7501831501831502 -> [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]::2048
4096: 1.5003663003663004 -> [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::4095
8192: 3.0007326007326007 -> [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]::4095

In [6]:
# int("110", 2)
# int(''.join(sar(0)), 2)
# ''.join([1, 1, 0])

### SAR: test

In [7]:
import unittest

class TestSar(unittest.TestCase):
    def setUp(self):
        self.nbit = 10
        self.vrefp = 1.0
        self.vrefm = 0.0
        self.vref = self.vrefp - self.vrefm
        self.qlevels = 2**self.nbit
        self.lsb = self.vref / (self.qlevels - 1)


        self.get_analog_from_bits_array = lambda code_list: int(''.join([str(bit) for bit in code_list]), 2)

    def test_fullscale_code(self):
        self.assertAlmostEqual(self.get_analog_from_bits_array(sar(self.vrefp)), self.qlevels - 1)

    def test_higher_than_fullscale_code(self):
        self.assertAlmostEqual(self.get_analog_from_bits_array(sar(2 * self.vrefp)), self.qlevels - 1)

    def test_negative_vin(self):
        self.assertAlmostEqual(self.get_analog_from_bits_array(sar(-10 * self.lsb)), 0)

    def test_bit_levels(self):
        for i in range(self.nbit):
            vin = (2**i) * self.lsb
            self.assertAlmostEqual(self.get_analog_from_bits_array(sar(vin)), 2**i)

    def test_all_levels(self):
        for i in range(2**nbit):
            vin = i * self.lsb
            # print(f"{vin} -> {sar(vin)}")
            self.assertAlmostEqual(self.get_analog_from_bits_array(sar(vin)), i)



if __name__ == "__main__":
    unittest.main(argv=[''], exit=False, verbosity=2)

test_all_levels (__main__.TestSar.test_all_levels) ... ok
test_bit_levels (__main__.TestSar.test_bit_levels) ... ok
test_fullscale_code (__main__.TestSar.test_fullscale_code) ... ok
test_higher_than_fullscale_code (__main__.TestSar.test_higher_than_fullscale_code) ... ok
test_negative_vin (__main__.TestSar.test_negative_vin) ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.058s

OK

In [8]:
print(get_analog_from_bits_array(sar(2**0 * adc.lsb)))
assert get_analog_from_bits_array(sar(2**0 * adc.lsb)) == 2**0
range(2**nbit)[-1]

1

1023

In [9]:
code = "".join([str(bit) for bit in sar(2**0 * adc.lsb)])
assert int(code, 2) == 2**0

In [17]:
import ipywidgets as ipw

vrefp_max = 2.5
@ipw.interact(vin = (0, vrefp_max, 0.1), nbit = (1, 15, 1), vrefp = (0.0, vrefp_max, 0.5), vrefm = (0.0, vrefp_max, 0.5))
def get_sar(vin, nbit, vrefp, vrefm):
    return sar(vin, nbit=nbit, vrefp=vrefp, vrefm=vrefm)

interactive(children=(FloatSlider(value=1.2000000000000002, description='vin', max=2.5), IntSlider(value=8, de…

## SAR: Calculations

### Setup

In [50]:
import os

from pathlib import Path

# data_path = Path(os.getcwd()).parent / "data"
data_path = Path(os.getcwd()) / "data"

# create data_path if does nto exit
data_path.mkdir(parents=True, exist_ok=True)

In [51]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(context="notebook", style="darkgrid", palette="pastel")

### DACOUT

In [29]:
nbit = 12
vrefp = 1.5

lsb = 2 * vrefp / (2**nbit - 1)
print(f"lsb: {lsb}")

vcm = 0.5 * vrefp
vin = 0.75
vinp = vcm + 0.5 * vin
vinm = vcm - 0.5 * vin

vthreshp = vrefp / 2
vthreshm = vrefp / 2

dacoutp = vcm + vthreshp - vinp
dacoutm = vcm + vthreshm - vinm

dacoutp, dacoutm

lsb: 0.0007326007326007326

(0.375, 1.125)

In [28]:
vfs = 1.49708

err = vrefp - vfs

err, err / lsb

(0.0029200000000000337, 3.985800000000046)

In [31]:
ideal_fs = 2**nbit - 1
adcout_fsm, adcout_fsp = 4095, 4076

errp, errm = ideal_fs - adcout_fsm, ideal_fs - adcout_fsp

errp, errm

(0, 19)

In [48]:
vrefp = 1.5
adc_diff = Adc(
    nbit = 12,
    vrefp = 2*vrefp,
    vrefm = 0.0,
    fs = 10e3
)
adc_diff_convert = lambda vin, vrefp=1.0: adc_diff.convert(vrefp + vin)
for i in range(nbit):
    _vin = 2**i * adc_diff.lsb
    code = adc_diff_convert(_vin, vrefp)
    print(f"i: {i}\t::\tvin:{_vin}::code: {code}")

i: 0	::	vin:0.0007326007326007326::code: 2048
i: 1	::	vin:0.0014652014652014652::code: 2050
i: 2	::	vin:0.0029304029304029304::code: 2052
i: 3	::	vin:0.005860805860805861::code: 2056
i: 4	::	vin:0.011721611721611722::code: 2064
i: 5	::	vin:0.023443223443223443::code: 2080
i: 6	::	vin:0.046886446886446886::code: 2112
i: 7	::	vin:0.09377289377289377::code: 2176
i: 8	::	vin:0.18754578754578755::code: 2304
i: 9	::	vin:0.3750915750915751::code: 2560
i: 10	::	vin:0.7501831501831502::code: 3072
i: 11	::	vin:1.5003663003663004::code: 4095

In [53]:

# data_path = Path(os.getcwd()).parent / "data"
data_path = Path(os.getcwd()) / "data"

# /content/data/saradc_out_linearity_bitshift250128.csv
adcout_sim = pd.read_csv(data_path / "saradc_out_linearity_bitshift250128.csv")
adcout_sim.columns = adcout_sim.columns.str.strip().str.lower().str.replace(" ", "_")
adcout_sim.head()

   adcoutm_at_eoc_x  adcoutm_at_eoc_y  adcoutp_at_eoc_x  adcoutp_at_eoc_y
0          -1.50000              4095          -1.50000                 0
1          -0.75000              3072          -0.75000              1023
2          -0.37500              2559          -0.37500              1536
3          -0.18750              2303          -0.18750              1792
4          -0.09375              2175          -0.09375              1920

In [57]:
adcout_sim["ideal_outp"] = adcout_sim["adcoutm_at_eoc_x"].apply(lambda x: adc_diff_convert(x, vrefp))
adcout_sim["errorp"] = adcout_sim["adcoutp_at_eoc_y"] - adcout_sim["ideal_outp"]

# adcout_sim.head(24)
adcout_sim

,adcoutm_at_eoc_x,adcoutm_at_eoc_y,adcoutp_at_eoc_x,adcoutp_at_eoc_y,ideal_outp,errorp
0,-1.500000,4095,-1.500000,0,0,0
1,-0.750000,3072,-0.750000,1023,1024,-1
2,-0.375000,2559,-0.375000,1536,1536,0
3,-0.187500,2303,-0.187500,1792,1792,0
4,-0.093750,2175,-0.093750,1920,1920,0
5,-0.046875,2111,-0.046875,1984,1984,0
6,-0.023438,2080,-0.023438,2015,2016,-1
7,-0.011719,2065,-0.011719,2030,2032,-2
8,-0.005859,2056,-0.005859,2039,2040,-1
9,-0.002930,2052,-0.002930,2043,2044,-1
10,-0.001465,2051,-0.001465,2044,2046,-2
11,-0.000732,2049,-0.000732,2046,2047,-1
12,-0.000366,2049,-0.000366,2046,2047,-1
13,0.000000,2048,0.000000,2047,2048,-1
14,0.000366,2048,0.000366,2047,2048,-1
15,0.000732,2048,0.000732,2047,2048,-1
16,0.001465,2048,0.001465,2047,2049,-2
17,0.002930,2048,0.002930,2047,2051,-4
18,0.005859,2048,0.005859,2047,2055,-8
19,0.011719,2048,0.011719,2047,2063,-16
20,0.023438,2048,0.023438,2047,2079,-32
21,0.046875,1984,0.046875,2111,2111,0
22,0.093750,1919,0.093750,2176,2175,1
23,0.187500,1792,0.187500,2303,2303,0
24,0.375000,1535,0.375000,2560,2559,1
25,0.750000,1027,0.750000,3068,3071,-3
26,1.500000,19,1.500000,4076,4095,-19

In [59]:
23e-3 / adc_diff.lsb

31.395

In [65]:
(1 * 2**nbit * 20 / 3600) / 24

0.9481481481481482